In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("sales_quality_dirty.csv")

In [2]:
df.head()

   OrderID   OrderDate     Product Quantity UnitPrice       City
0     9001  2026-05-01      Laptop        2     650.0    Chennai
1     9002  2026-05-02      mouse         5      18.5    chennai
2     9003  2026-05-03     Monitor        3     180.0  HYDERABAD
3     9004  not-a-date    Keyboard      two      32.0  Bengaluru
4     9005  2026-05-05  Headphones      NaN      45.0       Pune

In [3]:
df.head()

   OrderID   OrderDate     Product Quantity UnitPrice       City
0     9001  2026-05-01      Laptop        2     650.0    Chennai
1     9002  2026-05-02      mouse         5      18.5    chennai
2     9003  2026-05-03     Monitor        3     180.0  HYDERABAD
3     9004  not-a-date    Keyboard      two      32.0  Bengaluru
4     9005  2026-05-05  Headphones      NaN      45.0       Pune

In [4]:
df.shape

(26, 6)

In [5]:
df.columns

Index(['OrderID', 'OrderDate', 'Product', 'Quantity', 'UnitPrice', 'City'],
      dtype='str')

In [6]:
df.columns

Index(['OrderID', 'OrderDate', 'Product', 'Quantity', 'UnitPrice', 'City'],
      dtype='str')

In [7]:
df.isnull().sum()

OrderID      0
OrderDate    0
Product      0
Quantity     1
UnitPrice    0
City         1
dtype: int64

In [8]:
df[df.duplicated()]

    OrderID   OrderDate Product Quantity UnitPrice     City
25     9009  2026-05-09  Router        3      79.0  Kolkata

In [9]:
df[df.duplicated()]

    OrderID   OrderDate Product Quantity UnitPrice     City
25     9009  2026-05-09  Router        3      79.0  Kolkata

In [10]:
df = df.drop_duplicates()

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["Product"] = df["Product"].str.strip().str.title()

df["City"] = df["City"].str.strip().str.title()

In [13]:
print(df["Product"].unique())
print(df["City"].unique())

<StringArray>
[           'Laptop',             'Mouse',           'Monitor',
          'Keyboard',        'Headphones',            'Webcam',
      'External Ssd',           'Printer',            'Router',
     'Gaming Laptop',         'Usb Cable',            'Tablet',
        'Smartphone',           'Speaker',        'Power Bank',
     'Graphics Card',        'Microphone',        'Smartwatch',
        'Hard Drive',         'Projector',   'Docking Station',
      'Laptop Stand', 'Bluetooth Speaker']
Length: 23, dtype: str
<StringArray>
[      'Chennai',     'Hyderabad',     'Bengaluru',          'Pune',
        'Mumbai',             nan,         'Delhi',       'Kolkata',
        'Jaipur',       'Lucknow',     'Ahmedabad',    'Coimbatore',
 'Visakhapatnam',    'Vijayawada',      'Tirupati',        'Mysuru',
       'Madurai',        'Trichy',         'Salem']
Length: 19, dtype: str

In [14]:
df["OrderDate"] = pd.to_datetime(
    df["OrderDate"],
    errors="coerce"
)

In [15]:
df[df["OrderDate"].isna()]

   OrderID OrderDate   Product Quantity UnitPrice       City
3     9004       NaT  Keyboard      two      32.0  Bengaluru

In [16]:
df["Quantity"] = pd.to_numeric(
    df["Quantity"],
    errors="coerce"
)

df["UnitPrice"] = pd.to_numeric(
    df["UnitPrice"],
    errors="coerce"
)

In [17]:
df.dtypes

OrderID               int64
OrderDate    datetime64[us]
Product                 str
Quantity            float64
UnitPrice           float64
City                    str
dtype: object

In [18]:
df["Quantity"] = df["Quantity"].fillna(
    df["Quantity"].median()
)

df["UnitPrice"] = df["UnitPrice"].fillna(
    df["UnitPrice"].median()
)

In [19]:
df["City"] = df["City"].fillna("Unknown")

df["Product"] = df["Product"].fillna("Unknown")

In [20]:
def price_category(price):
    if pd.isna(price):
        return "Unknown"
    elif price < 100:
        return "Low"
    elif price < 500:
        return "Medium"
    else:
        return "High"

In [21]:
df["PriceCategory"] = df["UnitPrice"].apply(price_category)

In [22]:
df[["Product", "UnitPrice", "PriceCategory"]]

              Product   UnitPrice PriceCategory
0              Laptop     650.000          High
1               Mouse      18.500           Low
2             Monitor     180.000        Medium
3            Keyboard      32.000           Low
4          Headphones      45.000           Low
5              Webcam      99.995           Low
6        External Ssd      89.990           Low
7             Printer     155.000        Medium
8              Router      79.000           Low
9       Gaming Laptop    1450.000          High
10             Laptop     650.000          High
11          Usb Cable       7.990           Low
12             Tablet     320.000        Medium
13         Smartphone     499.000        Medium
14            Speaker      38.000           Low
15         Power Bank      25.000           Low
16      Graphics Card     899.000          High
17         Microphone      75.000           Low
18         Smartwatch     120.000        Medium
19         Hard Drive      69.000           Low
20          Projector     410.000        Medium
21    Docking Station     110.000        Medium
22       Laptop Stand      29.000           Low
23      Gaming Laptop  999999.000          High
24  Bluetooth Speaker      55.000           Low

In [23]:
df.nlargest(5, "UnitPrice")[
    ["OrderID", "Product", "UnitPrice", "City"]
]

    OrderID        Product  UnitPrice           City
23     9024  Gaming Laptop   999999.0         Mumbai
9      9010  Gaming Laptop     1450.0        Chennai
16     9017  Graphics Card      899.0  Visakhapatnam
0      9001         Laptop      650.0        Chennai
10     9011         Laptop      650.0        Chennai

In [24]:
Q1 = df["UnitPrice"].quantile(0.25)
Q3 = df["UnitPrice"].quantile(0.75)

IQR = Q3 - Q1

upper_bound = Q3 + 1.5 * IQR

df[df["UnitPrice"] > upper_bound][
    ["OrderID", "Product", "UnitPrice", "City"]
]

    OrderID        Product  UnitPrice     City
9      9010  Gaming Laptop     1450.0  Chennai
23     9024  Gaming Laptop   999999.0   Mumbai

In [25]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [26]:
df[[
    "OrderID",
    "Product",
    "Quantity",
    "UnitPrice",
    "PriceCategory",
    "Revenue"
]]

    OrderID            Product  Quantity   UnitPrice PriceCategory     Revenue
0      9001             Laptop       2.0     650.000          High    1300.000
1      9002              Mouse       5.0      18.500           Low      92.500
2      9003            Monitor       3.0     180.000        Medium     540.000
3      9004           Keyboard       2.0      32.000           Low      64.000
4      9005         Headphones       2.0      45.000           Low      90.000
5      9006             Webcam       1.0      99.995           Low      99.995
6      9007       External Ssd       2.0      89.990           Low     179.980
7      9008            Printer       1.0     155.000        Medium     155.000
8      9009             Router       3.0      79.000           Low     237.000
9      9010      Gaming Laptop       1.0    1450.000          High    1450.000
10     9011             Laptop       1.0     650.000          High     650.000
11     9012          Usb Cable      10.0       7.990           Low      79.900
12     9013             Tablet       2.0     320.000        Medium     640.000
13     9014         Smartphone       1.0     499.000        Medium     499.000
14     9015            Speaker       4.0      38.000           Low     152.000
15     9016         Power Bank       3.0      25.000           Low      75.000
16     9017      Graphics Card       1.0     899.000          High     899.000
17     9018         Microphone       2.0      75.000           Low     150.000
18     9019         Smartwatch       2.0     120.000        Medium     240.000
19     9020         Hard Drive       1.0      69.000           Low      69.000
20     9021          Projector       1.0     410.000        Medium     410.000
21     9022    Docking Station       2.0     110.000        Medium     220.000
22     9023       Laptop Stand       3.0      29.000           Low      87.000
23     9024      Gaming Laptop       1.0  999999.000          High  999999.000
24     9025  Bluetooth Speaker       2.0      55.000           Low     110.000