In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("sales_dirty.csv")

df.head()

   OrderID   OrderDate        Product Quantity UnitPrice       City
0     5001  2026-04-01         Laptop      2.0     650.0    Chennai
1     5002  2026-04-02          Mouse      5.0      18.5  Bengaluru
2     5003  2026-04-03        Monitor      2.0     180.0  Hyderabad
3     5004  2026-04-04       Keyboard      3.0      32.0     Mumbai
4     5005  2026-04-05  Gaming Laptop      1.0    1450.0       Pune

In [3]:
df.tail()

    OrderID   OrderDate       Product Quantity UnitPrice       City
60     5001  2026-04-20        Laptop      1.0     650.0    Chennai
61     5002  2026-04-21       Monitor      2.0     180.0  Hyderabad
62     5063  2026-04-22         Mouse     10.0      18.5    mUmBaI
63     5064  2026-04-23      Keyboard      4.0  999999.0  Bengaluru
64     5001  2026-04-24  External SSD      2.0     89.99       Pune

In [4]:
df.shape

(65, 6)

In [5]:
df.columns

Index(['OrderID', 'OrderDate', 'Product', 'Quantity', 'UnitPrice', 'City'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    65 non-null     int64
 1   OrderDate  64 non-null     str
 2   Product    64 non-null     str
 3   Quantity   64 non-null     str
 4   UnitPrice  64 non-null     str
 5   City       64 non-null     str
dtypes: int64(1), str(5)
memory usage: 3.2 KB

In [7]:
df.describe(include="all")

            OrderID   OrderDate Product Quantity UnitPrice     City
count     65.000000          64      64       64        64       64
unique          NaN          28      13        9        15       60
top             NaN  2026-04-01  Laptop      1.0     650.0  Chennai
freq            NaN           3       6       19         6        2
mean    5030.169231         NaN     NaN      NaN       NaN      NaN
std       18.841086         NaN     NaN      NaN       NaN      NaN
min     5001.000000         NaN     NaN      NaN       NaN      NaN
25%     5014.000000         NaN     NaN      NaN       NaN      NaN
50%     5030.000000         NaN     NaN      NaN       NaN      NaN
75%     5046.000000         NaN     NaN      NaN       NaN      NaN
max     5064.000000         NaN     NaN      NaN       NaN      NaN

In [8]:
df.isnull().sum()

OrderID      0
OrderDate    1
Product      1
Quantity     1
UnitPrice    1
City         1
dtype: int64

In [9]:
df.isnull().sum()[df.isnull().sum() > 0]

OrderDate    1
Product      1
Quantity     1
UnitPrice    1
City         1
dtype: int64

In [10]:
df.isnull().sum().sum()

np.int64(5)

In [11]:
df[df.isnull().any(axis=1)]

    OrderID   OrderDate        Product Quantity UnitPrice    City
5      5006  2026-04-06     Headphones      NaN      45.0   Delhi
8      5009  2026-04-09  Graphics Card      1.0       NaN  Jaipur
21     5022  2026-04-22            NaN      5.0      7.99   Erode
33     5034         NaN      USB Cable      5.0      7.99  Indore
48     5049  2026-04-21         Laptop      2.0     650.0     NaN

In [12]:
df[df.duplicated(subset="OrderID", keep=False)].sort_values("OrderID")

    OrderID   OrderDate       Product Quantity UnitPrice       City
0      5001  2026-04-01        Laptop      2.0     650.0    Chennai
60     5001  2026-04-20        Laptop      1.0     650.0    Chennai
64     5001  2026-04-24  External SSD      2.0     89.99       Pune
1      5002  2026-04-02         Mouse      5.0      18.5  Bengaluru
61     5002  2026-04-21       Monitor      2.0     180.0  Hyderabad

In [13]:
df.duplicated(subset="OrderID").sum()

np.int64(3)

In [14]:
df["OrderID"].value_counts()[df["OrderID"].value_counts() > 1]

OrderID
5001    3
5002    2
Name: count, dtype: int64

In [15]:
df.dtypes

OrderID      int64
OrderDate      str
Product        str
Quantity       str
UnitPrice      str
City           str
dtype: object

In [16]:
df["UnitPrice"] = pd.to_numeric(df["UnitPrice"], errors="coerce")

In [17]:
df["UnitPrice"]

0        650.00
1         18.50
2        180.00
3         32.00
4       1450.00
        ...
60       650.00
61       180.00
62        18.50
63    999999.00
64        89.99
Name: UnitPrice, Length: 65, dtype: float64

In [18]:
df["UnitPrice"].max()

np.float64(999999.0)

In [19]:
df.loc[df["UnitPrice"].idxmax(), ["Product", "UnitPrice"]]

Product      Keyboard
UnitPrice    999999.0
Name: 63, dtype: object

In [20]:
df[df["UnitPrice"] == df["UnitPrice"].max()][["Product", "UnitPrice", "City"]]

     Product  UnitPrice       City
63  Keyboard   999999.0  Bengaluru

In [21]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

In [22]:
df[["Quantity", "UnitPrice"]].isnull().sum()

Quantity     2
UnitPrice    2
dtype: int64

In [23]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [24]:
df[["OrderID", "Product", "Quantity", "UnitPrice", "City", "Revenue"]]

    OrderID        Product  Quantity  UnitPrice       City     Revenue
0      5001         Laptop       2.0     650.00    Chennai     1300.00
1      5002          Mouse       5.0      18.50  Bengaluru       92.50
2      5003        Monitor       2.0     180.00  Hyderabad      360.00
3      5004       Keyboard       3.0      32.00     Mumbai       96.00
4      5005  Gaming Laptop       1.0    1450.00       Pune     1450.00
..      ...            ...       ...        ...        ...         ...
60     5001         Laptop       1.0     650.00    Chennai      650.00
61     5002        Monitor       2.0     180.00  Hyderabad      360.00
62     5063          Mouse      10.0      18.50    mUmBaI       185.00
63     5064       Keyboard       4.0  999999.00  Bengaluru  3999996.00
64     5001   External SSD       2.0      89.99       Pune      179.98

[65 rows x 6 columns]

In [25]:
df[df["Revenue"].isnull()]

    OrderID   OrderDate        Product  Quantity  UnitPrice      City  Revenue
5      5006  2026-04-06     Headphones       NaN       45.0     Delhi      NaN
8      5009  2026-04-09  Graphics Card       1.0        NaN    Jaipur      NaN
24     5025  2026-04-25         Laptop       NaN      650.0  Warangal      NaN
29     5030  2026-04-02     Headphones       4.0        NaN     Surat      NaN

In [26]:
df["City"] = df["City"].astype("string").str.strip().str.title()

In [27]:
city_revenue = df.groupby("City")["Revenue"].sum(min_count=1)

In [28]:
city_revenue.sort_values(ascending=False)

City
Bengaluru        4000178.49
Ghaziabad         449500.00
Chennai             3250.00
Pune                1629.98
Aurangabad          1450.00
Mysuru              1450.00
Srinagar            1450.00
Patna               1300.00
Salem                899.00
Bhopal               899.00
Hyderabad            720.00
Jalandhar            360.00
Bhubaneswar          360.00
Vijayawada           360.00
Nagpur               360.00
Mumbai               281.00
Chandigarh           237.00
Tirunelveli          237.00
Prayagraj            237.00
Kochi                237.00
Jabalpur             237.00
Mangaluru            180.00
Shillong             180.00
Noida                180.00
Trichy               155.00
Aizawl               155.00
Rajkot               155.00
Ahmedabad            155.00
Faridabad            155.00
Coimbatore           109.00
Haridwar             109.00
Vellore              109.00
Varanasi             109.00
Gwalior              109.00
Tirupati              96.00
Cuttack               96.00
Jammu                 96.00
Nashik                96.00
Ranchi                92.50
Nizamabad             92.50
Ludhiana              92.50
Visakhapatnam         92.50
Imphal                89.99
Gurugram              89.99
Kolkata               89.99
Vadodara              89.99
Kanpur                39.95
Dehradun              39.95
Erode                 39.95
Lucknow               39.95
Indore                39.95
Agartala             -25.00
Guwahati           -4350.00
Delhi                   NaN
Jaipur                  NaN
Surat                   NaN
Warangal                NaN
Name: Revenue, dtype: float64

In [29]:
city_revenue.sort_values(ascending=False)

City
Bengaluru        4000178.49
Ghaziabad         449500.00
Chennai             3250.00
Pune                1629.98
Aurangabad          1450.00
Mysuru              1450.00
Srinagar            1450.00
Patna               1300.00
Salem                899.00
Bhopal               899.00
Hyderabad            720.00
Jalandhar            360.00
Bhubaneswar          360.00
Vijayawada           360.00
Nagpur               360.00
Mumbai               281.00
Chandigarh           237.00
Tirunelveli          237.00
Prayagraj            237.00
Kochi                237.00
Jabalpur             237.00
Mangaluru            180.00
Shillong             180.00
Noida                180.00
Trichy               155.00
Aizawl               155.00
Rajkot               155.00
Ahmedabad            155.00
Faridabad            155.00
Coimbatore           109.00
Haridwar             109.00
Vellore              109.00
Varanasi             109.00
Gwalior              109.00
Tirupati              96.00
Cuttack               96.00
Jammu                 96.00
Nashik                96.00
Ranchi                92.50
Nizamabad             92.50
Ludhiana              92.50
Visakhapatnam         92.50
Imphal                89.99
Gurugram              89.99
Kolkata               89.99
Vadodara              89.99
Kanpur                39.95
Dehradun              39.95
Erode                 39.95
Lucknow               39.95
Indore                39.95
Agartala             -25.00
Guwahati           -4350.00
Delhi                   NaN
Jaipur                  NaN
Surat                   NaN
Warangal                NaN
Name: Revenue, dtype: float64

In [30]:
city_summary = (
    df.groupby("City", dropna=False)
      .agg(
          TotalRevenue=("Revenue", "sum"),
          TotalQuantity=("Quantity", "sum"),
          NumberOfOrders=("OrderID", "nunique")
      )
      .sort_values("TotalRevenue", ascending=False)
)

city_summary

               TotalRevenue  TotalQuantity  NumberOfOrders
City
Bengaluru        4000178.49           10.0               3
Ghaziabad         449500.00          500.0               1
Chennai             3250.00            5.0               2
Pune                1629.98            3.0               2
Mysuru              1450.00            1.0               1
Aurangabad          1450.00            1.0               1
Srinagar            1450.00            1.0               1
Patna               1300.00            2.0               1
<NA>                1300.00            2.0               1
Bhopal               899.00            1.0               1
Salem                899.00            1.0               1
Hyderabad            720.00            4.0               2
Nagpur               360.00            2.0               1
Vijayawada           360.00            2.0               1
Bhubaneswar          360.00            2.0               1
Jalandhar            360.00            2.0               1
Mumbai               281.00           13.0               2
Kochi                237.00            3.0               1
Tirunelveli          237.00            3.0               1
Prayagraj            237.00            3.0               1
Jabalpur             237.00            3.0               1
Chandigarh           237.00            3.0               1
Mangaluru            180.00            4.0               1
Shillong             180.00            4.0               1
Noida                180.00            4.0               1
Faridabad            155.00            1.0               1
Trichy               155.00            1.0               1
Ahmedabad            155.00            1.0               1
Aizawl               155.00            1.0               1
Rajkot               155.00            1.0               1
Coimbatore           109.00            2.0               1
Vellore              109.00            2.0               1
Varanasi             109.00            2.0               1
Haridwar             109.00            2.0               1
Gwalior              109.00            2.0               1
Cuttack               96.00            3.0               1
Jammu                 96.00            3.0               1
Tirupati              96.00            3.0               1
Nashik                96.00            3.0               1
Visakhapatnam         92.50            5.0               1
Ludhiana              92.50            5.0               1
Nizamabad             92.50            5.0               1
Ranchi                92.50            5.0               1
Gurugram              89.99            1.0               1
Kolkata               89.99            1.0               1
Vadodara              89.99            1.0               1
Imphal                89.99            1.0               1
Dehradun              39.95            5.0               1
Indore                39.95            5.0               1
Erode                 39.95            5.0               1
Kanpur                39.95            5.0               1
Lucknow               39.95            5.0               1
Delhi                  0.00            0.0               1
Jaipur                 0.00            1.0               1
Surat                  0.00            4.0               1
Warangal               0.00            0.0               1
Agartala             -25.00            1.0               1
Guwahati           -4350.00           -3.0               1

In [31]:
df = df.dropna(subset=["Revenue"])

In [32]:
df.to_csv("sales_revenue_analysis.csv", index=False)

In [33]:
print("Rows remaining:", len(df))
print("Null values in Revenue:", df["Revenue"].isnull().sum())

Rows remaining: 61
Null values in Revenue: 0