In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("sales_dirty.csv")

df.head()

   OrderID   OrderDate        Product Quantity UnitPrice       City
0     5001  2026-04-01         Laptop      2.0     650.0    Chennai
1     5002  2026-04-02          Mouse      5.0      18.5  Bengaluru
2     5003  2026-04-03        Monitor      2.0     180.0  Hyderabad
3     5004  2026-04-04       Keyboard      3.0      32.0     Mumbai
4     5005  2026-04-05  Gaming Laptop      1.0    1450.0       Pune

In [3]:
df.head(5).isnull()

   OrderID  OrderDate  Product  Quantity  UnitPrice   City
0    False      False    False     False      False  False
1    False      False    False     False      False  False
2    False      False    False     False      False  False
3    False      False    False     False      False  False
4    False      False    False     False      False  False

In [4]:
df.head(5).isna()

   OrderID  OrderDate  Product  Quantity  UnitPrice   City
0    False      False    False     False      False  False
1    False      False    False     False      False  False
2    False      False    False     False      False  False
3    False      False    False     False      False  False
4    False      False    False     False      False  False

In [5]:
df.head(5).isnull().sum()

OrderID      0
OrderDate    0
Product      0
Quantity     0
UnitPrice    0
City         0
dtype: int64

In [6]:
df.isnull().sum()

OrderID      0
OrderDate    1
Product      1
Quantity     1
UnitPrice    1
City         1
dtype: int64

In [7]:
df5 = df.head(5).copy()

df5.dropna()

   OrderID   OrderDate        Product Quantity UnitPrice       City
0     5001  2026-04-01         Laptop      2.0     650.0    Chennai
1     5002  2026-04-02          Mouse      5.0      18.5  Bengaluru
2     5003  2026-04-03        Monitor      2.0     180.0  Hyderabad
3     5004  2026-04-04       Keyboard      3.0      32.0     Mumbai
4     5005  2026-04-05  Gaming Laptop      1.0    1450.0       Pune

In [8]:
df5["UnitPrice"] = pd.to_numeric(
    df5["UnitPrice"], errors="coerce"
)

print("Mean:", df5["UnitPrice"].mean())
print("Median:", df5["UnitPrice"].median())

Mean: 466.1
Median: 180.0

In [9]:
df5["Quantity"] = pd.to_numeric(
    df5["Quantity"], errors="coerce"
)

df5["Quantity"] = df5["Quantity"].fillna(
    df5["Quantity"].median()
)

df5

   OrderID   OrderDate        Product  Quantity  UnitPrice       City
0     5001  2026-04-01         Laptop       2.0      650.0    Chennai
1     5002  2026-04-02          Mouse       5.0       18.5  Bengaluru
2     5003  2026-04-03        Monitor       2.0      180.0  Hyderabad
3     5004  2026-04-04       Keyboard       3.0       32.0     Mumbai
4     5005  2026-04-05  Gaming Laptop       1.0     1450.0       Pune

In [10]:
df5["UnitPrice"] = df5["UnitPrice"].fillna(
    df5["UnitPrice"].median()
)

df5

   OrderID   OrderDate        Product  Quantity  UnitPrice       City
0     5001  2026-04-01         Laptop       2.0      650.0    Chennai
1     5002  2026-04-02          Mouse       5.0       18.5  Bengaluru
2     5003  2026-04-03        Monitor       2.0      180.0  Hyderabad
3     5004  2026-04-04       Keyboard       3.0       32.0     Mumbai
4     5005  2026-04-05  Gaming Laptop       1.0     1450.0       Pune