In [2]:
import numpy as np

In [3]:
marks = np.array([85, 90, 78, 92, 88, 76, 95, 89, 81, 94])

print(marks)

[85 90 78 92 88 76 95 89 81 94]

In [4]:
print("Total:", np.sum(marks))

Total: 868

In [5]:
print("Average:", np.mean(marks))

Average: 86.8

In [6]:
print("Minimum:", np.min(marks))

Minimum: 76

In [7]:
print("Maximum:", np.max(marks))

Maximum: 95

In [8]:
print("Median:", np.median(marks))
print("Standard deviation:", np.std(marks))

Median: 88.5
Standard deviation: 6.273754856543249

In [9]:
print("Shape:", marks.shape)
print("Dimensions:", marks.ndim)
print("Number of elements:", marks.size)
print("Data type:", marks.dtype)

Shape: (10,)
Dimensions: 1
Number of elements: 10
Data type: int64

In [10]:
import pandas as pd

In [11]:

data = {
    "Movie": [
        "Okkadu", "Athadu", "Pokiri", "Khaleja",
        "Dookudu", "Businessman", "Srimanthudu",
        "Bharat Ane Nenu", "Maharshi", "Guntur Kaaram"
    ],
    "Year": [2003, 2005, 2006, 2010, 2011, 2012, 2015, 2018, 2019, 2024],
    "Rating": [8.0, 8.2, 8.1, 7.6, 7.4, 7.2, 7.8, 7.5, 7.0, 6.0],
    "Budget_Cr": [10, 12, 15, 30, 35, 40, 50, 65, 100, 150]
}

df = pd.DataFrame(data)

df

             Movie  Year  Rating  Budget_Cr
0           Okkadu  2003     8.0         10
1           Athadu  2005     8.2         12
2           Pokiri  2006     8.1         15
3          Khaleja  2010     7.6         30
4          Dookudu  2011     7.4         35
5      Businessman  2012     7.2         40
6      Srimanthudu  2015     7.8         50
7  Bharat Ane Nenu  2018     7.5         65
8         Maharshi  2019     7.0        100
9    Guntur Kaaram  2024     6.0        150

In [12]:
df.head()

     Movie  Year  Rating  Budget_Cr
0   Okkadu  2003     8.0         10
1   Athadu  2005     8.2         12
2   Pokiri  2006     8.1         15
3  Khaleja  2010     7.6         30
4  Dookudu  2011     7.4         35

In [13]:
df.tail()

             Movie  Year  Rating  Budget_Cr
5      Businessman  2012     7.2         40
6      Srimanthudu  2015     7.8         50
7  Bharat Ane Nenu  2018     7.5         65
8         Maharshi  2019     7.0        100
9    Guntur Kaaram  2024     6.0        150

In [14]:
df.shape

(10, 4)

In [15]:
df.columns

Index(['Movie', 'Year', 'Rating', 'Budget_Cr'], dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Movie      10 non-null     str
 1   Year       10 non-null     int64
 2   Rating     10 non-null     float64
 3   Budget_Cr  10 non-null     int64
dtypes: float64(1), int64(2), str(1)
memory usage: 452.0 bytes

In [17]:
df.isnull().sum()

Movie        0
Year         0
Rating       0
Budget_Cr    0
dtype: int64

In [18]:
df.describe()

              Year     Rating   Budget_Cr
count    10.000000  10.000000   10.000000
mean   2012.300000   7.480000   50.700000
std       6.733828   0.649444   44.364776
min    2003.000000   6.000000   10.000000
25%    2007.000000   7.250000   18.750000
50%    2011.500000   7.550000   37.500000
75%    2017.250000   7.950000   61.250000
max    2024.000000   8.200000  150.000000

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df["Movie_Age"] = 2026 - df["Year"]

df

             Movie  Year  Rating  Budget_Cr  Movie_Age
0           Okkadu  2003     8.0         10         23
1           Athadu  2005     8.2         12         21
2           Pokiri  2006     8.1         15         20
3          Khaleja  2010     7.6         30         16
4          Dookudu  2011     7.4         35         15
5      Businessman  2012     7.2         40         14
6      Srimanthudu  2015     7.8         50         11
7  Bharat Ane Nenu  2018     7.5         65          8
8         Maharshi  2019     7.0        100          7
9    Guntur Kaaram  2024     6.0        150          2

In [21]:
print("Average Rating:", df["Rating"].mean())
print("Maximum Rating:", df["Rating"].max())
print("Minimum Rating:", df["Rating"].min())
print("Median Rating:", df["Rating"].median())
print("Total Budget:", df["Budget_Cr"].sum())
print("Average Budget:", df["Budget_Cr"].mean())

Average Rating: 7.4799999999999995
Maximum Rating: 8.2
Minimum Rating: 6.0
Median Rating: 7.55
Total Budget: 507
Average Budget: 50.7

In [22]:
df[df["Year"] > 2010]

             Movie  Year  Rating  Budget_Cr  Movie_Age
4          Dookudu  2011     7.4         35         15
5      Businessman  2012     7.2         40         14
6      Srimanthudu  2015     7.8         50         11
7  Bharat Ane Nenu  2018     7.5         65          8
8         Maharshi  2019     7.0        100          7
9    Guntur Kaaram  2024     6.0        150          2

In [23]:
df[df["Rating"] > 7.5]

         Movie  Year  Rating  Budget_Cr  Movie_Age
0       Okkadu  2003     8.0         10         23
1       Athadu  2005     8.2         12         21
2       Pokiri  2006     8.1         15         20
3      Khaleja  2010     7.6         30         16
6  Srimanthudu  2015     7.8         50         11

In [24]:
df[df["Budget_Cr"] > 50]

             Movie  Year  Rating  Budget_Cr  Movie_Age
7  Bharat Ane Nenu  2018     7.5         65          8
8         Maharshi  2019     7.0        100          7
9    Guntur Kaaram  2024     6.0        150          2

In [25]:
df[(df["Year"] > 2010) & (df["Rating"] > 7.5)]

         Movie  Year  Rating  Budget_Cr  Movie_Age
6  Srimanthudu  2015     7.8         50         11

In [26]:
df.sort_values(by="Rating", ascending=False)

             Movie  Year  Rating  Budget_Cr  Movie_Age
1           Athadu  2005     8.2         12         21
2           Pokiri  2006     8.1         15         20
0           Okkadu  2003     8.0         10         23
6      Srimanthudu  2015     7.8         50         11
3          Khaleja  2010     7.6         30         16
7  Bharat Ane Nenu  2018     7.5         65          8
4          Dookudu  2011     7.4         35         15
5      Businessman  2012     7.2         40         14
8         Maharshi  2019     7.0        100          7
9    Guntur Kaaram  2024     6.0        150          2